name: Java + Prettier Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint-java-with-prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Si vous voulez compiler/tester le code Java avant le check Prettier,
      # vous pouvez lancer Gradle ou Maven ici :
      #
      # - name: Build/test with Gradle
      #   run: ./gradlew build

      - name: Set up Node (pour installer Prettier)
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Prettier + plugin Java
        run: npm install --save-dev prettier prettier-plugin-java

      - name: Run Prettier check
        # --check retourne un code d'erreur si le format n'est pas bon.
        # Pour corriger automatiquement, vous pouvez faire "--write" (en local).
        run: npx prettier --check "**/*.java"